FORMAT: 1A
HOST: http://stickerprinter.apiblueprint.org/

# stickerprinter

Sticker printer is a web application that allows the uploading and the purchasing of stickers

## Purchasing a sticker [/purchase]
### Upload and pay for a sticker [POST]

Upload a PNG and payment details and recieve a JWT valid for 14 days

+ Attributes
    + sticker: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg== (string) - Base64 PNG data URL for the sticker
    + stripeToken: tok_1Ca86c2eZvKYlo2CpM4c0yMD (string) - Charge token from the Stripe form input
+ Request (application/x-www-form-urlencoded)

+ Response 202 (text/jwt)
    + Headers
    + Body
    
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3OTZjNjhkZC03YjhlLTQ4MjktODgzYS1lZWRlNWU2OTA0MDgiLCJpYXQiOjE1MTYyMzkwMjJ9.fp4axvF2M9WW9De6w0HviqAUogN13xVkkntYywzTbos

+ Response 403 (text/plain)
    + Body
    
            Payment token invalid

+ Response 406 (text/plain)
    + Body
    
            Sticker invalid
        
## Printing a sticker [/print/{token}]
+ Parameters
    + token - a JWT to verify

### Verify token and download it [GET]
+ Response 202 (image/png)
    + Headers
    + Body
    
            data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==

+ Response 403 (text/plain)
    + Body
    
            Token invalid